services:
    okvpn_datadog.exception_listener:
        class: Okvpn\Bundle\DatadogBundle\EventListener\ExceptionListener
        arguments:
          - '@okvpn_datadog.logger'
          - '@okvpn_datadog.services.skip_capture'
        tags:
            - { name: kernel.event_listener, event: kernel.exception,  method: onKernelException }
            - { name: kernel.event_listener, event: console.error, method: onConsoleError }
            - { name: kernel.event_listener, event: console.exception, method: onConsoleError }

    okvpn_datadog.flush_buffer.listener:
        class: Okvpn\Bundle\DatadogBundle\EventListener\DatadogFlushBufferListener
        arguments: ['@okvpn_datadog.logger', '@okvpn_datadog.monolog.log_handler']
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
            - { name: kernel.event_listener, event: console.terminate, method: onCliTerminate }
